[package]
name = "frnaf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"

[dependencies.bevy_kira_audio]
version = "0.10.0"
default-features = false
features = [
  "wav",
  "mp3",
]